import type { VideoSkill } from "@/types/video";

export const videoSkillLabels: Record<VideoSkill, string> = {
  reading: "リーディング",
  listening: "リスニング",
  math_ia: "数学 I A",
  math_iibc: "数学 II BC",
  japanese_modern_takeuchi: "現代文（竹内）",
  japanese_modern_kikuma: "現代文（菊間）",
  japanese_modern_shibata: "現代文（柴田）",
  japanese_classical_sekijima: "古文（関島）",
  japanese_kanbun_sekijima: "漢文（関島）",
  japanese_classical_wada: "古文（和田）",
  world_history: "世界史",
  world_history_new_trends: "世界史新傾向",
  japanese_history: "日本史",
  geography: "地理",
  geography_practice: "地理実戦",
  physics: "物理",
  physics_basic: "物理基礎",
  chemistry: "化学",
  chemistry_basic: "化学基礎",
  biology: "生物",
  biology_basic: "生物基礎",
  earth_science_basic: "地学基礎",
  information_i: "情報 I",
  politics_economics: "政治・経済",
  public_civics: "公共",
  ethics: "倫理",
  secondary_todai: "東大2次",
  secondary_kyodai: "京大2次",
  secondary_nagoya: "名大2次",
  secondary_hamamatsu_medical: "浜松医科大2次",
};

export const videoSkillOrder: VideoSkill[] = [
  "reading",
  "listening",
  "math_ia",
  "math_iibc",
  "japanese_modern_takeuchi",
  "japanese_modern_kikuma",
  "japanese_modern_shibata",
  "japanese_classical_sekijima",
  "japanese_kanbun_sekijima",
  "japanese_classical_wada",
  "physics",
  "physics_basic",
  "chemistry",
  "chemistry_basic",
  "biology",
  "biology_basic",
  "earth_science_basic",
  "world_history",
  "world_history_new_trends",
  "japanese_history",
  "geography",
  "geography_practice",
  "politics_economics",
  "public_civics",
  "ethics",
  "information_i",
  "secondary_todai",
  "secondary_kyodai",
  "secondary_nagoya",
  "secondary_hamamatsu_medical",
];
